const CONFIG={arrivalMs:20000,rampMs:60000,targetCycleMs:10000,sessionMs:300000,paces:{settle:{inhale:.4,label:'Settle · 4 in, 6 out'},balanced:{inhale:.5,label:'Balanced · 5 in, 5 out'},gentle:{inhale:5/11,label:'Gentle · 5 in, 6 out'}}};
const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
const canvas=$('#flow-canvas'),ctx=canvas.getContext('2d',{alpha:false});
const intro=$('#intro'),session=$('#session'),results=$('#results'),settings=$('#settings');
const phaseEl=$('#phase'),cueEl=$('#cue'),detailEl=$('#detail'),timeEl=$('#time'),progressEl=$('#progress-fill'),orbit=$('#breath-orbit');
let state={running:false,start:0,ended:false,pace:localStorage.getItem('ml-flow-pace')||'settle',pointer:0,targetPointer:0,trail:[],raf:0};
function resize(){const dpr=Math.min(devicePixelRatio||1,2);canvas.width=innerWidth*dpr;canvas.height=innerHeight*dpr;canvas.style.width=innerWidth+'px';canvas.style.height=innerHeight+'px';ctx.setTransform(dpr,0,0,dpr,0,0)}
addEventListener('resize',resize);resize();
function easeInOut(t){return .5-.5*Math.cos(Math.PI*Math.max(0,Math.min(1,t)))}
function cycleFor(elapsed){if(elapsed<CONFIG.arrivalMs)return 0;const ramp=Math.min(1,(elapsed-CONFIG.arrivalMs)/CONFIG.rampMs);return 7000+(CONFIG.targetCycleMs-7000)*easeInOut(ramp)}
function breathState(elapsed){if(elapsed<CONFIG.arrivalMs)return{stage:'Arrive',cue:'Let the ride settle.',detail:'Breathe normally for a moment',env:.42,phase:'arrive',cycle:0};const cycle=cycleFor(elapsed);const local=(elapsed-CONFIG.arrivalMs)%cycle;const inhaleRatio=CONFIG.paces[state.pace].inhale;const inhaleMs=cycle*inhaleRatio;if(local<inhaleMs){const p=easeInOut(local/inhaleMs);return{stage:elapsed<CONFIG.arrivalMs+CONFIG.rampMs?'Follow':'Settle',cue:'Inhale',detail:'Gather the light',env:.45+.5*p,phase:'inhale',cycle}}const p=easeInOut((local-inhaleMs)/(cycle-inhaleMs));return{stage:elapsed<CONFIG.arrivalMs+CONFIG.rampMs?'Follow':'Settle',cue:'Exhale',detail:'Let the path carry you',env:.95-.5*p,phase:'exhale',cycle}}
function draw(now){const w=innerWidth,h=innerHeight,elapsed=state.running?Math.min(now-state.start,CONFIG.sessionMs):0,b=breathState(elapsed);state.pointer+=(state.targetPointer-state.pointer)*.035;ctx.fillStyle='#02080b';ctx.fillRect(0,0,w,h);
 const horizon=h*.46,glow=50+160*b.env;let g=ctx.createRadialGradient(w/2,horizon,0,w/2,horizon,glow*2.4);g.addColorStop(0,`rgba(64,210,220,${.08+.12*b.env})`);g.addColorStop(1,'rgba(2,8,11,0)');ctx.fillStyle=g;ctx.fillRect(0,0,w,h);
 ctx.fillStyle='#061118';ctx.beginPath();ctx.moveTo(0,horizon+20);for(let x=0;x<=w;x+=w/8){const y=horizon-18-Math.sin(x*.013+now*.00004)*20-Math.sin(x*.027)*13;ctx.lineTo(x,y)}ctx.lineTo(w,h);ctx.lineTo(0,h);ctx.fill();
 ctx.strokeStyle=`rgba(111,247,232,${.12+.18*b.env})`;ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(0,horizon);ctx.lineTo(w,horizon);ctx.stroke();
 const pathX=w/2+state.pointer*w*.12;ctx.beginPath();ctx.moveTo(w*.22,h);ctx.quadraticCurveTo(pathX-w*.06,h*.72,w/2,horizon);ctx.quadraticCurveTo(pathX+w*.05,h*.64,w*.78,h);ctx.closePath();let road=ctx.createLinearGradient(0,horizon,0,h);road.addColorStop(0,'rgba(8,24,29,.85)');road.addColorStop(1,'rgba(2,8,11,.98)');ctx.fillStyle=road;ctx.fill();
 ctx.strokeStyle=`rgba(111,247,232,${.25+.45*b.env})`;ctx.shadowColor='rgba(111,247,232,.5)';ctx.shadowBlur=15;ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(w*.22,h);ctx.quadraticCurveTo(pathX-w*.06,h*.72,w/2,horizon);ctx.stroke();ctx.beginPath();ctx.moveTo(w*.78,h);ctx.quadraticCurveTo(pathX+w*.05,h*.64,w/2,horizon);ctx.stroke();ctx.shadowBlur=0;
 const markY=h*.68,markX=w/2+state.pointer*w*.11;state.trail.push({x:markX,y:markY,life:1});if(state.trail.length>90)state.trail.shift();ctx.lineCap='round';for(let i=1;i<state.trail.length;i++){const a=state.trail[i-1],p=state.trail[i],alpha=i/state.trail.length*.18;ctx.strokeStyle=`rgba(111,247,232,${alpha})`;ctx.lineWidth=1+3*i/state.trail.length;ctx.beginPath();ctx.moveTo(a.x,a.y+(state.trail.length-i)*1.6);ctx.lineTo(p.x,p.y+(state.trail.length-i-1)*1.6);ctx.stroke()}
 ctx.save();ctx.translate(markX,markY);ctx.rotate(state.pointer*.12);ctx.strokeStyle='#b8fff7';ctx.shadowColor='#6ff7e8';ctx.shadowBlur=20;ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(-18,12);ctx.lineTo(-7,-10);ctx.lineTo(0,2);ctx.lineTo(7,-10);ctx.lineTo(18,12);ctx.stroke();ctx.restore();
 orbit.style.setProperty('--breath-scale',String(.55+b.env*.45));orbit.style.setProperty('--breath-opacity',String(.25+b.env*.5));if(state.running){phaseEl.textContent=b.stage;cueEl.textContent=b.cue;detailEl.textContent=b.detail;const left=Math.max(0,CONFIG.sessionMs-elapsed);timeEl.textContent=`${Math.floor(left/60000)}:${String(Math.floor(left%60000/1000)).padStart(2,'0')}`;progressEl.style.width=`${elapsed/CONFIG.sessionMs*100}%`;if(elapsed>=CONFIG.sessionMs&&!state.ended)finishSession()}state.raf=requestAnimationFrame(draw)}
function startSession(){intro.hidden=true;results.hidden=true;session.hidden=false;state.running=true;state.ended=false;state.start=performance.now();state.trail=[]}
function finishSession(){state.running=false;state.ended=true;session.hidden=true;results.hidden=false;const key='ml-flow-sessions';const sessions=Number(localStorage.getItem(key)||0)+1;localStorage.setItem(key,String(sessions));$('#session-count').textContent=sessions===1?'Your first reset is complete.':`${sessions} resets completed.`}
function setPace(p){state.pace=p;localStorage.setItem('ml-flow-pace',p);$$('[data-pace]').forEach(b=>b.setAttribute('aria-checked',String(b.dataset.pace===p)));$('#pace-label').textContent=CONFIG.paces[p].label}
$$('[data-start]').forEach(b=>b.addEventListener('click',startSession));$('#finish').addEventListener('click',finishSession);$('#again').addEventListener('click',startSession);$('#home').addEventListener('click',()=>location.href='dashboard.html');$('#journal').addEventListener('click',()=>{const ride=new URLSearchParams(location.search).get('ride');location.href=ride?`journal.html?ride=${encodeURIComponent(ride)}`:'journal.html'});$('#close').addEventListener('click',()=>history.length>1?history.back():location.assign('dashboard.html'));$('#settings-open').addEventListener('click',()=>settings.hidden=false);$('#settings-close').addEventListener('click',()=>settings.hidden=true);$$('[data-pace]').forEach(b=>b.addEventListener('click',()=>setPace(b.dataset.pace)));
function point(e){const r=canvas.getBoundingClientRect();state.targetPointer=Math.max(-1,Math.min(1,((e.clientX-r.left)/r.width-.5)*2))}canvas.addEventListener('pointermove',point);canvas.addEventListener('pointerdown',e=>{canvas.setPointerCapture?.(e.pointerId);point(e)});canvas.addEventListener('pointerup',()=>state.targetPointer=0);canvas.addEventListener('pointercancel',()=>state.targetPointer=0);
setPace(state.pace);requestAnimationFrame(draw);